// Targeted ADO Steps XML and legacy Markdown compatibility, adapted from the supplied harness.
import {emptyAdoMetadata} from './ado-metadata.mjs';
import {requireValue} from './config.mjs';
export function parameterNames(xml) {
  if (!xml || /^\s*<parameters\s*\/>\s*$/i.test(xml) || /^\s*<parameters>\s*<\/parameters>\s*$/i.test(xml)) return [];
  requireValue(typeof xml === 'string' && /<parameters\b/.test(xml), 'parameters-without-data');
  const names = [...xml.matchAll(/<param\b[^>]*\bname=(?:"([^"]+)"|'([^']+)')[^>]*\/?\s*>/g)].map(match => decodeEntities(match[1] ?? match[2]));
  requireValue(names.length > 0 && new Set(names.map(name => name.toLowerCase())).size === names.length && names.every(name => /^[A-Za-z_][\w -]{0,79}$/.test(name)), 'parameters-without-data');
  return names;
}
export function slugify(s, max = 50) {
  return String(s).toLowerCase()
    .replace(/[^a-z0-9؀-ۿ]+/g, '-') // keep Arabic letters readable
    .replace(/^-+|-+$/g, '')
    .slice(0, max)
    .replace(/-+$/g, '') || 'untitled';
}

/** "user login & OTP" -> "UserLoginOtp" — seed for the <Feature>Tests.spec.ts suggestion. */
export function pascalCase(s) {
  const words = String(s).replace(/[^A-Za-z0-9]+/g, ' ').trim().split(/\s+/).filter(Boolean);
  return words.map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join('') || 'Feature';
}

export function decodeEntities(s) {
  return String(s)
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&nbsp;/g, ' ')
    .replace(/&rsquo;/g, '’').replace(/&lsquo;/g, '‘')
    .replace(/&rdquo;/g, '”').replace(/&ldquo;/g, '“')
    .replace(/&ndash;/g, '–').replace(/&mdash;/g, '—').replace(/&hellip;/g, '…')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

/** HTML fragment -> plain text (block tags become newlines).
 *  Content arrives XML-escaped inside the Steps field (&lt;DIV&gt;…), so decode
 *  first to expose the tags, strip them, then decode once more for HTML-level
 *  entities (&amp;amp; is the double-escaped form of a literal &). */
export function htmlToText(html) {
  if (!html) return '';
  let t = decodeEntities(html);
  t = t
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/(p|div|li|tr|h[1-6])\s*>/gi, '\n')
    .replace(/<li\b[^>]*>/gi, '- ')
    .replace(/<\/?[A-Za-z][^>]*>/g, ''); // tag-shaped only — literal "a < b, c > d" text survives
  t = decodeEntities(t);
  return t.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').replace(/[ \t]{2,}/g, ' ').trim();
}

export function parseStepsXml(xml) {
  const out = [];
  if (!xml) return out;
  // The self-closing branch is tried before the open+close branch at every attrs
  // length, so a self-closing <compref/> (or <step/>) can never swallow following
  // siblings by pairing with a later close tag (regression-checked in --self-test).
  const nodeRe = /<(step|compref)\b([^>]*?)(?:\/\s*>|>([\s\S]*?)<\/\1\s*>)/g;
  let m;
  while ((m = nodeRe.exec(xml)) !== null) {
    const tag = m[1];
    const attrs = m[2] || '';
    const inner = m[3] || '';
    if (tag === 'compref') {
      const ref = (attrs.match(/ref="(\d+)"/) || [])[1];
      if (ref) out.push({ kind: 'sharedRef', ref: Number(ref) });
      continue;
    }
    const type = (attrs.match(/type="([^"]*)"/) || [, ''])[1];
    // Same self-closing-first shape: an empty <parameterizedString/> keeps its
    // positional slot (action vs expected) instead of shifting the next one into it.
    const params = [...inner.matchAll(/<parameterizedString\b[^>]*?(?:\/\s*>|>([\s\S]*?)<\/parameterizedString\s*>)/g)]
      .map((p) => htmlToText(p[1] || ''));
    out.push({
      kind: 'step',
      type,
      action: params[0] || '',
      expected: params[1] || '',
    });
  }
  return out;
}

// ---------- spec rendering ----------

export function renderSpec({ tc, planId, suiteId, suiteName, storyId, storyTitle, target, org, project }) {
  const story = storyId !== undefined;
  const lines = [];
  lines.push(`# Spec: ${tc.title}  (TC ${tc.id})`);
  lines.push('');
  lines.push(`Target: ${target || 'https://example.com  <!-- set portalUrl in environments/<env>.json -->'}`);
  lines.push(`Type: ${tc.tags.length ? tc.tags.join(', ') : 'functional'} — stateful chain`);
  lines.push(`Source: Azure DevOps TC ${tc.id} — ${story ? `story ${storyId} (${storyTitle})` : `plan ${planId}, suite ${suiteId} (${suiteName})`} — org ${org}, project ${project}`);
  lines.push(`<!-- GENERATED by scripts/fetch-ado-${story ? 'story' : 'suite'}.mjs (raw fetch). The automate-test REFINE phase`);
  lines.push(`     may restructure steps for executability (scope preserved, changes logged below).`);
  lines.push(`     Refetch keeps files with a "## Refinement log" — overwrite only with --force. -->`);
  lines.push('');
  lines.push('## Acceptance criteria');
  const expected = tc.steps.filter((s) => s.expected).map((s) => `- ${s.expected.replace(/\n+/g, ' ')}`);
  lines.push(...(expected.length ? expected : ['- Source expectations are missing; refinement is required before execution.']));

  lines.push('');
  lines.push('## Scenario steps  (stateful — run in order, in one session)');
  let n = 0;
  for (const s of tc.steps) {
    n += 1;
    const action = s.action.replace(/\n+/g, ' ').trim() || '(no action text)';
    const exp = s.expected ? ` — Expected: ${s.expected.replace(/\n+/g, ' ').trim()}` : '';
    const shared = s.fromShared ? ` _(from shared steps ${s.fromShared})_` : '';
    lines.push(`${n}. ${action}${exp}${shared}`);
  }
  if (n === 0) lines.push('1. (test case has no steps recorded in Azure DevOps — verify manually)');
  lines.push('');
  lines.push('## Notes');
  lines.push(`- This spec mirrors Azure DevOps test case ${tc.id}; report defects against it.`);
  if (!emptyAdoMetadata(tc.parameters, 'parameters')) lines.push(`- Parameterized test case — iterate the data table below once per row.`);
  if (!emptyAdoMetadata(tc.dataTable, 'NewDataSet')) {
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(tc.dataTable, null, 2));
    lines.push('```');
  }
  lines.push('');
  return lines.join('\n');
}

// ---------- offline self-test (no network, no PAT) ----------

export function selfTest() {
  const sampleXml =
    '<steps id="0" last="7">' +
    '<step id="2" type="ActionStep">' +
    '<parameterizedString isformatted="true">&lt;DIV&gt;&lt;P&gt;Open the portal &amp;amp; wait for load&lt;/P&gt;&lt;/DIV&gt;</parameterizedString>' +
    '<parameterizedString isformatted="true"/>' +
    '</step>' +
    '<compref id="4" ref="9999"/>' +
    '<step id="6" type="ValidateStep">' +
    '<parameterizedString isformatted="true">Click &lt;B&gt;Login&lt;/B&gt;</parameterizedString>' +
    '<parameterizedString isformatted="true">Dashboard header is visible&lt;BR/&gt;No console errors</parameterizedString>' +
    '</step></steps>';
  const steps = parseStepsXml(sampleXml);
  const checks = [
    ['3 nodes parsed', steps.length === 3],
    ['action decoded', steps[0].action === 'Open the portal & wait for load'],
    ['actionstep empty expected', steps[0].expected === ''],
    ['shared ref captured', steps[1].kind === 'sharedRef' && steps[1].ref === 9999],
    ['validate action', steps[2].action === 'Click Login'],
    ['validate expected multiline', steps[2].expected === 'Dashboard header is visible\nNo console errors'],
  ];
  const spec = renderSpec({
    tc: { id: 101, title: 'Self test case', tags: ['smoke'], steps: steps.filter((s) => s.kind === 'step'), parameters: null, dataTable: null },
    planId: 1, suiteId: 2, suiteName: 'Self Suite', target: 'https://example.test', org: 'org', project: 'proj',
  });
  checks.push(['spec has title', spec.includes('# Spec: Self test case  (TC 101)')]);
  checks.push(['spec has stateful marker', spec.includes('stateful — run in order, in one session')]);
  checks.push(['pascalCase', pascalCase('user login & OTP') === 'UserLoginOtp']);
  checks.push(['pascalCase arabic falls back', pascalCase('تسجيل الدخول') === 'Feature']);
  // regression: self-closing tags must not swallow siblings or shift param slots
  const tricky = parseStepsXml(
    '<steps id="0" last="8">' +
    '<compref id="2" ref="100"/>' +
    '<step id="4" type="ActionStep"><parameterizedString isformatted="true">Middle step</parameterizedString><parameterizedString isformatted="true"/></step>' +
    '<compref id="6" ref="200"><ignored/></compref>' +
    '<step id="8" type="ValidateStep"><parameterizedString isformatted="true"/><parameterizedString isformatted="true">Expected only</parameterizedString></step>' +
    '</steps>');
  checks.push(['self-closing compref keeps siblings', tricky.length === 4]);
  checks.push(['middle step survives', tricky[1] && tricky[1].action === 'Middle step']);
  checks.push(['children-form compref parsed', tricky[2] && tricky[2].kind === 'sharedRef' && tricky[2].ref === 200]);
  checks.push(['empty first param keeps its slot', tricky[3] && tricky[3].action === '' && tricky[3].expected === 'Expected only']);
  // regression: literal comparison text must not be stripped as a "tag"
  checks.push(['literal < > text survives', htmlToText('verify amount &lt; 500 and count &gt; 3') === 'verify amount < 500 and count > 3']);
  let failed = 0;
  for (const [name, ok] of checks) {
    console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}`);
    if (!ok) failed += 1;
  }
  if (failed) throw new Error(`self-test: ${failed} check(s) failed`);
  console.log('self-test: all checks passed');
}
