import * as fs from 'fs/promises'; // Use fs/promises for async operations
import * as path from 'path';
import { allureConfig } from './src/config/reporting';

/**
 * Run-start hygiene: ensures the Allure results directory exists and clears any
 * results left over from the previous run, so the report generated by
 * `global-teardown.ts` never silently mixes runs. (The generated HTML reports
 * themselves are preserved per run under `reports/allure-history/` by the teardown —
 * only the raw result files are disposable.)
 *
 * Runs once per run, outside any worker — no test context, so no `test.step()`,
 * `test.info()`, or Allure attachments here.
 *
 * A failed clear corrupts report integrity (stale results would merge into the new
 * report), so unlike the teardown's report plumbing this script rethrows on failure.
 */
module.exports = async () => {
    const resultsDir = allureConfig.resultsDir;
    console.log('🔄 Ensuring Allure results directory exists...');

    try {
        // 1. Ensure the directory exists (recursive: true prevents error if it exists)
        await fs.mkdir(resultsDir, { recursive: true });
        console.log(`📁 Directory ensured: ${resultsDir}`);

        // 2. Read the directory contents
        const files = await fs.readdir(resultsDir);

        if (files.length === 0) {
            console.log('✅ Allure results directory is already clear.');
            return;
        }

        // 3. Clear existing files concurrently using Promise.all
        console.log(`🧹 Clearing ${files.length} existing Allure result files...`);
        const unlinkPromises = files.map(file => {
            const filePath = path.join(resultsDir, file);
            // Use fs.rm to remove files/directories gracefully, with force for files
            return fs.rm(filePath, { force: true, recursive: true, maxRetries: 3, retryDelay: 100 });
        });

        await Promise.all(unlinkPromises);
        console.log('✅ Allure results cleared.');

    } catch (error) {
        console.error(`❌ Failed to ensure or clear Allure results directory: ${resultsDir}`, error);
        throw error;
    }
};
